services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn qlygia.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2"
    volumes:
      - .:/app
    ports:
      - "80:8000"  # Map port 80 of EC2 to port 8000 of container
    environment:
      - SECRET_KEY=django-production-secret-key-npv-qlygia-2026
      - DEBUG=False
      - ALLOWED_HOSTS=*
