# Generated by Django 5.2.14 on 2026-05-28 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoiTac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nha_xe', models.CharField(max_length=255)),
                ('dia_chi', models.CharField(blank=True, max_length=500, null=True)),
                ('ten_don_vi_xuat_hoa_don', models.CharField(blank=True, max_length=255, null=True)),
                ('dia_chi_xuat_hoa_don', models.CharField(blank=True, max_length=500, null=True)),
                ('ma_so_thue', models.CharField(blank=True, max_length=50, null=True)),
                ('so_tai_khoan', models.CharField(blank=True, max_length=100, null=True)),
                ('ngan_hang', models.CharField(blank=True, max_length=255, null=True)),
                ('nguoi_dai_dien', models.CharField(blank=True, max_length=255, null=True)),
                ('tinh_san_sang', models.BooleanField(default=True)),
                ('chat_luong', models.IntegerField(blank=True, null=True)),
                ('co_hop_dong', models.BooleanField(default=False)),
                ('ten_zalo', models.CharField(blank=True, max_length=255, null=True)),
                ('thoi_han_thanh_toan', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiaCoSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_xe', models.CharField(max_length=100)),
                ('gia_co_so', models.FloatField()),
                ('ngay_ap_dung', models.DateField()),
                ('so_khoi', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TuyenXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_tuyen', models.CharField(max_length=50, unique=True)),
                ('tinh_nhan', models.CharField(max_length=100)),
                ('huyen_nhan', models.CharField(max_length=100)),
                ('tinh_giao', models.CharField(max_length=100)),
                ('huyen_giao', models.CharField(max_length=100)),
                ('trang_thai', models.CharField(default='HoatDong', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BaoGiaThongTinXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tai_trong_tan', models.FloatField()),
                ('kich_thuoc', models.CharField(blank=True, max_length=255, null=True)),
                ('loai_thung', models.CharField(blank=True, max_length=100, null=True)),
                ('co_ghep_hang_khong', models.BooleanField(default=False)),
                ('co_chiu_qua_tai_khong', models.BooleanField(default=False)),
                ('ghi_chu_nang_luc', models.TextField(blank=True, null=True)),
                ('co_di_nhieu_diem_khong', models.BooleanField(default=False)),
                ('di_1_hay_2_chieu', models.IntegerField(default=1)),
                ('muc_gia_chap_nhan', models.FloatField()),
                ('thoi_han_thanh_toan', models.CharField(blank=True, max_length=255, null=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('doi_tac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bao_gia', to='core.doitac')),
                ('tuyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bao_gia', to='core.tuyenxe')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuBaoGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia_cu', models.FloatField()),
                ('gia_moi', models.FloatField()),
                ('ngay_doi_gia', models.DateTimeField(auto_now_add=True)),
                ('bao_gia_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su', to='core.baogiathongtinxe')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuGiaCoSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia_cu', models.FloatField()),
                ('gia_moi', models.FloatField()),
                ('gia_xang', models.FloatField(blank=True, null=True)),
                ('ly_do_doi', models.CharField(blank=True, max_length=500, null=True)),
                ('ngay_doi', models.DateTimeField(auto_now_add=True)),
                ('gia_co_so_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su', to='core.giacoso')),
            ],
        ),
        migrations.AddField(
            model_name='giacoso',
            name='tuyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gia_co_so', to='core.tuyenxe'),
        ),
    ]
