# Generated by Django 5.2.14 on 2026-05-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doitac',
            name='tinh_san_sang',
            field=models.CharField(choices=[('Cao', 'Cao'), ('Trung bình', 'Trung bình'), ('Thấp', 'Thấp')], default='Trung bình', max_length=50),
        ),
    ]
