# Generated by Django 5.2.14 on 2026-05-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_doitac_tinh_san_sang'),
    ]

    operations = [
        migrations.AddField(
            model_name='doitac',
            name='ma_nha_xe',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
