# Generated by Django 5.2.14 on 2026-05-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doitac_ma_nha_xe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baogiathongtinxe',
            name='ghi_chu_nang_luc',
        ),
        migrations.AddField(
            model_name='doitac',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
    ]
