# Generated by Django 5.2.14 on 2026-05-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_baogiathongtinxe_ghi_chu_nang_luc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doitac',
            name='nguoi_quan_ly',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doitac',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
