# Generated by Django 5.2.14 on 2026-05-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_doitac_nguoi_quan_ly_doitac_so_dien_thoai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baogiathongtinxe',
            name='thoi_han_thanh_toan',
        ),
        migrations.AddField(
            model_name='lichsubaogia',
            name='gia_xang',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichsubaogia',
            name='ly_do_doi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lichsubaogia',
            name='nguoi_doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
