# Generated by Django 4.2.8 on 2026-05-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_baogiathongtinxe_thoi_han_thanh_toan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baogiathongtinxe',
            name='so_khoi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
