# Generated by Django 4.2.8 on 2026-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_baogiathongtinxe_so_khoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='baogiathongtinxe',
            name='ngay_ket_thuc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
