# Generated by Django 4.2.8 on 2026-05-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_baogiathongtinxe_ngay_ket_thuc'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsubaogia',
            name='ngay_ket_thuc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
