# Generated by Django 5.2.14 on 2026-06-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lichsubaogia_ngay_ket_thuc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baogiathongtinxe',
            name='so_khoi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='giacoso',
            name='so_khoi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
