# Generated by Django 5.2.14 on 2026-06-01 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_baogiathongtinxe_so_khoi_alter_giacoso_so_khoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeXuatGiaCoSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_xe', models.CharField(max_length=100)),
                ('so_khoi', models.CharField(blank=True, max_length=50, null=True)),
                ('gia_hien_tai', models.FloatField(blank=True, null=True)),
                ('gia_de_xuat', models.FloatField()),
                ('ly_do_de_xuat', models.TextField()),
                ('nguoi_de_xuat', models.CharField(max_length=255)),
                ('trang_thai', models.CharField(choices=[('ChoDuyet', 'Chờ duyệt'), ('DaDuyet', 'Đã duyệt'), ('TuChoi', 'Từ chối')], default='ChoDuyet', max_length=50)),
                ('ly_do_tu_choi', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('tuyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='de_xuat_gia', to='core.tuyenxe')),
            ],
        ),
    ]
