# Generated by Django 5.2.14 on 2026-06-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dexuatgiacoso'),
    ]

    operations = [
        migrations.AddField(
            model_name='baogiathongtinxe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doitac',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giacoso',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
