# Generated by Django 5.2.14 on 2026-06-02 02:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_baogiathongtinxe_is_deleted_doitac_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baogiathongtinxe',
            name='ngay_bat_dau',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lichsubaogia',
            name='ngay_bat_dau',
            field=models.DateField(blank=True, null=True),
        ),
    ]
