# Generated by Django 5.2.14 on 2026-06-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_baogiathongtinxe_ngay_bat_dau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doitac',
            name='phi_boc_xep',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doitac',
            name='phi_di_qua_tai',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doitac',
            name='phi_rot_diem',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
