# Generated by Django 5.2.14 on 2026-06-03 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_doitac_phi_boc_xep_doitac_phi_di_qua_tai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baogiathongtinxe',
            name='ngay_ket_thuc',
        ),
    ]
