# Generated by Django 5.2.14 on 2026-06-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_baogiathongtinxe_ngay_ket_thuc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dexuatgiacoso',
            name='ly_do_tu_choi',
        ),
    ]
