# Generated by Django 5.2.14 on 2026-06-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_dexuatgiacoso_ly_do_tu_choi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dexuatgiacoso',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
