# Generated by Django 5.2.14 on 2026-06-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_dexuatgiacoso_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doitac',
            options={'verbose_name': 'Đối tác', 'verbose_name_plural': 'Đối tác'},
        ),
        migrations.AlterField(
            model_name='doitac',
            name='ten_nha_xe',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='huyen_giao',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='huyen_nhan',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='tinh_giao',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='tinh_nhan',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
