# Generated by Django 5.2.14 on 2026-06-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_doitac_options_alter_doitac_ten_nha_xe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doitac',
            name='ma_nha_xe',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
