# Generated by Django 6.0.6 on 2026-06-10 07:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CauHinhLoaiXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_xe', models.CharField(max_length=50, unique=True, verbose_name='Loại xe (Tấn)')),
                ('so_khoi_mac_dinh', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số khối mặc định')),
                ('thu_tu', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Cấu hình Loại xe & Số khối',
                'verbose_name_plural': 'Cấu hình Loại xe & Số khối',
                'ordering': ['thu_tu', 'loai_xe'],
            },
        ),
        migrations.AlterModelOptions(
            name='baogiathongtinxe',
            options={'verbose_name': 'Báo giá thông tin xe', 'verbose_name_plural': 'Báo giá thông tin xe'},
        ),
        migrations.AlterModelOptions(
            name='dexuatgiacoso',
            options={'verbose_name': 'Đề xuất giá cơ sở', 'verbose_name_plural': 'Đề xuất giá cơ sở'},
        ),
        migrations.AlterModelOptions(
            name='giacoso',
            options={'verbose_name': 'Giá cơ sở', 'verbose_name_plural': 'Giá cơ sở'},
        ),
        migrations.AlterModelOptions(
            name='lichsubaogia',
            options={'verbose_name': 'Lịch sử báo giá', 'verbose_name_plural': 'Lịch sử báo giá'},
        ),
        migrations.AlterModelOptions(
            name='lichsugiacoso',
            options={'verbose_name': 'Lịch sử giá cơ sở', 'verbose_name_plural': 'Lịch sử giá cơ sở'},
        ),
        migrations.AlterModelOptions(
            name='tuyenxe',
            options={'verbose_name': 'Tuyến xe', 'verbose_name_plural': 'Tuyến xe'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Hồ sơ nhân sự', 'verbose_name_plural': 'Hồ sơ nhân sự'},
        ),
        migrations.AlterField(
            model_name='baogiathongtinxe',
            name='co_chiu_qua_tai_khong',
            field=models.BooleanField(default=False, verbose_name='Có chịu quá tải không'),
        ),
        migrations.AlterField(
            model_name='baogiathongtinxe',
            name='co_di_nhieu_diem_khong',
            field=models.BooleanField(default=False, verbose_name='Có đi nhiều điểm không'),
        ),
        migrations.AlterField(
            model_name='baogiathongtinxe',
            name='co_ghep_hang_khong',
            field=models.BooleanField(default=False, verbose_name='Có ghép hàng không'),
        ),
        migrations.AlterField(
            model_name='baogiathongtinxe',
            name='di_1_hay_2_chieu',
            field=models.IntegerField(default=1, verbose_name='Đi 1 hay 2 chiều'),
        ),
        migrations.AlterField(
            model_name='baogiathongtinxe',
            name='doi_tac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bao_gia', to='core.doitac', verbose_name='Đối tác'),
        ),
        migrations.AlterField(
            model_name='baogiathongtinxe',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Đã xóa'),
        ),
        migrations.AlterField(
            model_name='baogiathongtinxe',
            name='kich_thuoc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kích thước'),
        ),
        migrations.AlterField(
            model_name='baogiathongtinxe',
            name='loai_thung',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại thùng'),
        ),
        migrations.AlterField(
            model_name='baogiathongtinxe',
            name='muc_gia_chap_nhan',
            field=models.FloatField(verbose_name='Mức giá chấp nhận'),
        ),
        migrations.AlterField(
            model_name='baogiathongtinxe',
            name='ngay_bat_dau',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='baogiathongtinxe',
            name='ngay_cap_nhat',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='baogiathongtinxe',
            name='so_khoi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Số khối'),
        ),
        migrations.AlterField(
            model_name='baogiathongtinxe',
            name='tai_trong_tan',
            field=models.FloatField(verbose_name='Tải trọng (tấn)'),
        ),
        migrations.AlterField(
            model_name='baogiathongtinxe',
            name='tuyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bao_gia', to='core.tuyenxe', verbose_name='Tuyến xe'),
        ),
        migrations.AlterField(
            model_name='dexuatgiacoso',
            name='gia_de_xuat',
            field=models.FloatField(verbose_name='Giá đề xuất'),
        ),
        migrations.AlterField(
            model_name='dexuatgiacoso',
            name='gia_hien_tai',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá hiện tại'),
        ),
        migrations.AlterField(
            model_name='dexuatgiacoso',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Đã đọc'),
        ),
        migrations.AlterField(
            model_name='dexuatgiacoso',
            name='loai_xe',
            field=models.CharField(max_length=100, verbose_name='Loại xe'),
        ),
        migrations.AlterField(
            model_name='dexuatgiacoso',
            name='ly_do_de_xuat',
            field=models.TextField(verbose_name='Lý do đề xuất'),
        ),
        migrations.AlterField(
            model_name='dexuatgiacoso',
            name='ngay_cap_nhat',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='dexuatgiacoso',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='dexuatgiacoso',
            name='nguoi_de_xuat',
            field=models.CharField(max_length=255, verbose_name='Người đề xuất'),
        ),
        migrations.AlterField(
            model_name='dexuatgiacoso',
            name='so_khoi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Số khối'),
        ),
        migrations.AlterField(
            model_name='dexuatgiacoso',
            name='trang_thai',
            field=models.CharField(choices=[('ChoDuyet', 'Chờ duyệt'), ('DaDuyet', 'Đã duyệt'), ('TuChoi', 'Từ chối')], default='ChoDuyet', max_length=50, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='dexuatgiacoso',
            name='tuyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='de_xuat_gia', to='core.tuyenxe', verbose_name='Tuyến xe'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='chat_luong',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chất lượng'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='co_hop_dong',
            field=models.BooleanField(default=False, verbose_name='Có hợp đồng'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='dia_chi_xuat_hoa_don',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ xuất hóa đơn'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Đã xóa'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='ma_nha_xe',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Mã nhà xe'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='ma_so_thue',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã số thuế'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='ngan_hang',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ngân hàng'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='nguoi_dai_dien',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Người đại diện'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='nguoi_quan_ly',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Người quản lý'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='phi_boc_xep',
            field=models.FloatField(blank=True, null=True, verbose_name='Phí bốc xếp'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='phi_di_qua_tai',
            field=models.FloatField(blank=True, null=True, verbose_name='Phí đi quá tải'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='phi_rot_diem',
            field=models.FloatField(blank=True, null=True, verbose_name='Phí rớt điểm'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='so_tai_khoan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Số tài khoản'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='ten_don_vi_xuat_hoa_don',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên đơn vị xuất hóa đơn'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='ten_nha_xe',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Tên nhà xe'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='ten_zalo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên Zalo'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='thoi_han_thanh_toan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thời hạn thanh toán'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='tinh_san_sang',
            field=models.CharField(choices=[('Cao', 'Cao'), ('Trung bình', 'Trung bình'), ('Thấp', 'Thấp')], default='Trung bình', max_length=50, verbose_name='Tính sẵn sàng'),
        ),
        migrations.AlterField(
            model_name='giacoso',
            name='gia_co_so',
            field=models.FloatField(verbose_name='Giá cơ sở'),
        ),
        migrations.AlterField(
            model_name='giacoso',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Đã xóa'),
        ),
        migrations.AlterField(
            model_name='giacoso',
            name='loai_xe',
            field=models.CharField(max_length=100, verbose_name='Loại xe'),
        ),
        migrations.AlterField(
            model_name='giacoso',
            name='ngay_ap_dung',
            field=models.DateField(verbose_name='Ngày áp dụng'),
        ),
        migrations.AlterField(
            model_name='giacoso',
            name='so_khoi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Số khối'),
        ),
        migrations.AlterField(
            model_name='giacoso',
            name='tuyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gia_co_so', to='core.tuyenxe', verbose_name='Tuyến xe'),
        ),
        migrations.AlterField(
            model_name='lichsubaogia',
            name='bao_gia_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su', to='core.baogiathongtinxe', verbose_name='Báo giá đối tác'),
        ),
        migrations.AlterField(
            model_name='lichsubaogia',
            name='gia_cu',
            field=models.FloatField(verbose_name='Giá cũ'),
        ),
        migrations.AlterField(
            model_name='lichsubaogia',
            name='gia_moi',
            field=models.FloatField(verbose_name='Giá mới'),
        ),
        migrations.AlterField(
            model_name='lichsubaogia',
            name='gia_xang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá xăng'),
        ),
        migrations.AlterField(
            model_name='lichsubaogia',
            name='ly_do_doi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Lý do đổi'),
        ),
        migrations.AlterField(
            model_name='lichsubaogia',
            name='ngay_bat_dau',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='lichsubaogia',
            name='ngay_doi_gia',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đổi giá'),
        ),
        migrations.AlterField(
            model_name='lichsubaogia',
            name='ngay_ket_thuc',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='lichsubaogia',
            name='nguoi_doi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Người đổi'),
        ),
        migrations.AlterField(
            model_name='lichsugiacoso',
            name='gia_co_so_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su', to='core.giacoso', verbose_name='Giá cơ sở'),
        ),
        migrations.AlterField(
            model_name='lichsugiacoso',
            name='gia_cu',
            field=models.FloatField(verbose_name='Giá cũ'),
        ),
        migrations.AlterField(
            model_name='lichsugiacoso',
            name='gia_moi',
            field=models.FloatField(verbose_name='Giá mới'),
        ),
        migrations.AlterField(
            model_name='lichsugiacoso',
            name='gia_xang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá xăng'),
        ),
        migrations.AlterField(
            model_name='lichsugiacoso',
            name='ly_do_doi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Lý do đổi'),
        ),
        migrations.AlterField(
            model_name='lichsugiacoso',
            name='ngay_doi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đổi'),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='huyen_giao',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Huyện giao'),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='huyen_nhan',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Huyện nhận'),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='ma_tuyen',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã tuyến'),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='tinh_giao',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Tỉnh giao'),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='tinh_nhan',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Tỉnh nhận'),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='trang_thai',
            field=models.CharField(default='HoatDong', max_length=50, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('ThueNgoai', 'Thuê ngoài')], default='ThueNgoai', max_length=20, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản'),
        ),
    ]
