# Generated by Django 6.0.6 on 2026-06-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cauhinhloaixe_alter_baogiathongtinxe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cauhinhloaixe',
            options={'ordering': ['loai_xe'], 'verbose_name': 'Cấu hình Loại xe & Số khối', 'verbose_name_plural': 'Cấu hình Loại xe & Số khối'},
        ),
        migrations.RemoveField(
            model_name='cauhinhloaixe',
            name='so_khoi_mac_dinh',
        ),
        migrations.RemoveField(
            model_name='cauhinhloaixe',
            name='thu_tu',
        ),
        migrations.AddField(
            model_name='cauhinhloaixe',
            name='khoi_den',
            field=models.FloatField(blank=True, null=True, verbose_name='Đến khối'),
        ),
        migrations.AddField(
            model_name='cauhinhloaixe',
            name='khoi_tu',
            field=models.FloatField(blank=True, null=True, verbose_name='Từ khối'),
        ),
    ]
